### ISSUE TITLE
Cannot find module 'object-assign'

### ISSUE THREAD

**Issue by kparperi** [sindresorhus/ipify#5]
Hey, great work! Just installed it and run the simple example you have on your page and got this error.
I am assuming this is a dependency that isn't listed?

module.js:338
    throw err;
          ^
Error: Cannot find module 'object-assign'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/ipify/node_modules/got/index.js:8:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by kparperi** [comment]
It's asking me for all sorts of dependencies: object-assign, infinity-agent...

**Comment by floatdrop** [comment]
@kparperi seems like `npm` problem. Ipify relies on [`got`](https://github.com/sindresorhus/got/blob/master/package.json#L51) which have those dependencies in `package.json`. Try to clean npm cache and reinstall ipify.

**Comment by kparperi** [comment]
Good shout! works fine now, thanks :)
